import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import { useDispatch } from "react-redux";
import { Banner } from "../components/Banner";
import { FooterComponent } from "../components/Footer";
import { Header } from "../components/Header";
import { MobileAppsInfo } from "../components/MobileAppInfo";
import { PopularMarkets } from "../components/PopularMarkets";
import { ProductView } from "../components/ProductsView";
import { asyncGetHomeDatas } from "../store/asyncActions.js/asyncGetHomeDatas";
import styles from "../styles/Home.module.css";

export default function Home() {
  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(asyncGetHomeDatas());
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Header />
      </Header>
      <main style={{ backgroundColor: "#f9f9f9", paddingBottom: "50px" }}>
        <Banner />
        <PopularMarkets />
        <ProductView />
        <MobileAppsInfo />
      </main>

      <footer>
        <FooterComponent />
      </footer>
    </div>
  );
}
